# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  #External monitor brightness control
  hardware.i2c.enable = true;

  #Added for GPU

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      libva
      intel-media-driver
      #nvidia-vaapi-driver
    ];
  };
  #
  #   hardware.nvidia = {
  #     modesetting.enable = true;
  #     open = false;
  #     nvidiaSettings = true;
  #   };
  #
  #   services.xserver.videoDrivers = ["nvidia"];
  #
  #   hardware.nvidia.prime = {
  #     offload = {
  #       enable = true;
  #       enableOffloadCmd = true;
  #     };
  #     # Make sure to use the correct Bus ID values for your system!
  #     intelBusId = "PCI:0:2:0";
  #     nvidiaBusId = "PCI:01:0:0";
  #     # amdgpuBusId = "PCI:54:0:0"; For AMD GPU
  #   };

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "vmd" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/c9e44b4c-439f-493a-8f6e-fdb40f80390a";

  fileSystems."/.swapvol" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=swap"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/823F-27FF";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  swapDevices = [
    {
      device = "/.swapvol/swapfile";
      priority = 10;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
